Neos:
  EventSourcing:
    EventStore:
      stores:
        'Ttree.Voting:EventStream':
          boundedContexts:
            'Ttree.Voting': true

          storage: 'Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage'

          storageOptions:

            eventTableName: 'ttree_voting_eventstream'
